export const ADD_ITEM_TO_CART = "ADD-ELEMENT_TO_CART"
export const REMOVE_ITEM_FROM_CART = "REMOVE_ELEMENT_FROM_CART"
export const ADD_ADDITIONAL_ITEM = "ADD_ADDITIONAL_ITEM"
export const CHANGE_ITEM_PROPERTY = "CHANGE_ITEM_PROPERTY"